/**
 * TimePuncher
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hans.tschan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DayPunchesVm {
    userboid?: string;

    day?: number;

    month?: number;

    year?: number;

    punches?: Array<models.Punch>;

    daytotal?: number;

}
