/**
 * TimePuncher
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hans.tschan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Punch {
    time?: string;

    timedec?: number;

    /**
     * True means enter work, Fals means leave work.
     */
    direction?: boolean;

    /**
     * The timestamp of the creation of this value.
     */
    created?: Date;

    /**
     * The timestamp of the last update of this value.
     */
    updated?: Date;

    punchid?: number;

}
