#!/usr/bin/env groovy

node {
    stage('scmstage'){
        git changelog: false, poll: false, url: '${THE_REPO}'    
        
    }
    stage('prime'){
        def status1 = powershell(returnStatus: true, script: 'Copy-Item $env:PROJECT_CONFIG/timepuncher-client-config-timepuncher.ch.ts $env:WORKSPACE/TpMaterial/src/app/timepuncher-client-config.ts')
		if ( status1 == 0){
			echo 'Copy ok'
		}
		else {
			echo 'Copy failed'
		}
    }
    stage('install'){
        dir('TpMaterial') {
            bat 'npm install'
        }
        dir('TpDotNetCore') {
            bat 'dotnet restore'
        }
        dir('TpIonic') {
            bat 'npm install'
        }
    }
    stage('build'){
        dir('TpMaterial'){
            bat 'ng build --prod'
        }
    }
}
