#!/usr/bin/env groovy

node {
    stage('prime'){
        def status1 = powershell(returnStatus: true, script: 'Copy-Item c:/sites/configdata/timepuncher-client-config-timepuncher.ch.ts $env:TP_WORKSPACE/TpMaterial/src/app/timepuncher-client-config.ts')
		if ( status1 == 0){
			echo 'Copy ok'
		}
		else {
			echo 'Copy failed'
		}
    }
    stage('prepare'){
        git changelog: false, poll: false, url: 'C:\\sites\\Bonobo.Git.Server\\App_Data\\Repositories\\Tp'    
        
    }
    stage('install'){
        dir('TpMaterial') {
            bat 'npm install'
        }
        dir('TpDotNetCore') {
            bat 'dotnet restore'
        }
        dir('TpIonic') {
            bat 'npm install'
        }
    }
    stage('build'){
        dir('TpMaterial'){
            bat 'ng build --prod'
        }
    }
}
